import { RestSchool } from '@/secondary/school/RestSchool';

const defaultRestSchool: RestSchool = {
  id: '03KJN0025W4',
  fechaUltimoReporte: '2020-06-16',
  localidad: 'LA CANDELARIA',
  municipioId: '008',
  entidadId: '03',
  nombre: 'CURSO COMUNITARIO DE EDUCACION PREESCOLAR',
  indiceAsistenciaDocentes: 1,
  indiceAsistenciaAdmin: -1,
  nivel: 'PREESCOLAR',
  cct: '03KJN0025W',
  turno: '4',
  hayClases: 1,
  modalidad: 'PREESCOLAR COMUNITARIO',
  municipio: 'LOS CABOS',
  cod_localidad: '0063',
  domicilio: 'NINGUNO NINGUNO',
  cod_inmueble: '03INM0636F',
  sostenimiento: 'PÚBLICO',
  alumnas: 1,
  alumnos: 5,
  sumaAlumnos: 6,
  docentes: 1,
  grupos: 1,
  director: 0,
  subdirector: 0,
  atps: 0,
  educfis: 0,
  admin: 0,
  intenden: 0,
  otros: 0,
  tipoAbasAgua: 2,
  contServAgua: 2,
  aguaLavamanos: 1,
  lavamanos: 2,
  jabon: 1,
  toallas: 3,
  sanitizante: 1,
  botesBasura: 2,
  tipoDrenaje: 2,
  espacios: 1,
  comite: 1,
  alterna_asis: 1,
  inaalumnas: 0,
  inaalumnos: 0,
  inaalum_causa1: 0,
  inaalum_causa2: 0,
  inaalum_causa3: 0,
  inaalum_causa4: 0,
  inaalum_causa5: 0,
  inaalum_causaotro: '',
  sumaInaDocentes: 0,
  inadoc_causa1: 0,
  inadoc_causa2: 0,
  inadoc_causa3: 0,
  inadoc_causa4: 0,
  inadoc_causaotro: '',
  sumaInaAdministrativos: 0,
  inaadm_causa1: 0,
  inaadm_causa2: 0,
  inaadm_causa3: 0,
  inaadm_causa4: 0,
  inaadm_causaotro: '',
  comentarios: '',
  indiceAsistenciaAlumnado: 1,
  indiceInasistenciaAlumnas: 0,
  indiceInasistenciaAlumnos: 0,
  alum_prog: 3,
  alimentos: 1,
  alimentosdif: -1,
  alimentosetc: 1,
  alimentosedo: -1,
  alimentosotro: 1,
  alimentosotro_txt: '',
  bebederos: 5,
  wcalumnas: 2,
  wcalumnos: 2,
  accionvisita: -1,
  accionllamada: 1,
  accionbeca: 1,
  accionninguna: -1,
  escuelanuestra: 1,
  indiceAlumnosSobreInasistencias: -1,
  indiceAlumnasSobreInasistencias: -1,
  contservelectrica: 3,
  internet: 1,
};

export const restSchool = (override: Partial<RestSchool> = {}) => ({
  ...defaultRestSchool,
  ...override,
});
