import { School } from '@/domain/school/School';

export interface RestSchool {
  id: string;
  localidad: string;
  municipioId: string;
  entidadId: string;
  nombre: string;
  indiceAsistenciaAlumnado: number;
  indiceAsistenciaAlumnas: number;
  indiceAsistenciaAlumnos: number;
  indiceAsistenciaDocentes: number;
  indiceAsistenciaAdmin: number;
  nivel: string;
  cct: string;
  turno: string;
  hayClases: 1;
  modalidad: string;
  municipio: string;
  cod_localidad: string;
  domicilio: string;
  cod_inmueble: string;
  sostenimiento: string;
  alumnas: number;
  alumnos: number;
  sumaAlumnos: number;
  docentes: number;
  grupos: number;
  director: number;
  subdirector: number;
  atps: number;
  educfis: number;
  admin: number;
  intenden: number;
  otros: number;
  tipoAbasAgua: number;
  contServAgua: number;
  aguaLavamanos: number;
  lavamanos: number;
  jabon: number;
  toallas: number;
  sanitizante: number;
  botesBasura: number;
  tipoDrenaje: number;
  espacios: number;
  comite: number;
  alterna_asis: number;
  sumaInaAlumnas: number;
  sumaInaAlumnos: number;
  inaalum_causa1: number;
  inaalum_causa2: number;
  inaalum_causa3: number;
  inaalum_causa4: number;
  inaalum_causa5: number;
  inaalum_causaotro: string;
  sumaInaDocentes: number;
  inadoc_causa1: number;
  inadoc_causa2: number;
  inadoc_causa3: number;
  inadoc_causa4: number;
  inadoc_causaotro: string;
  sumaInaAdministrativos: number;
  inaadm_causa1: number;
  inaadm_causa2: number;
  inaadm_causa3: number;
  inaadm_causa4: number;
  inaadm_causaotro: string;
  comentarios: string;
  indiceAlumnasSobreInasistencias: number;
  indiceAlumnosSobreInasistencias: number;
  alum_prog: number;
}

export const toSchool = (restSchool: RestSchool): School => ({
  id: restSchool.id,
  locality: restSchool.localidad,
  municipalityId: restSchool.municipioId,
  stateId: restSchool.entidadId,
  name: restSchool.nombre,
  studentAttendance: restSchool.indiceAsistenciaAlumnado,
  femaleStudentAttendance: restSchool.indiceAsistenciaAlumnas,
  maleStudentAttendance: restSchool.indiceAsistenciaAlumnos,
  teacherAttendance: restSchool.indiceAsistenciaDocentes,
  adminAttendance: restSchool.indiceAsistenciaAdmin,
  level: restSchool.nivel,
  workCenterKey: restSchool.cct,
  turn: restSchool.turno,
  givesClasses: restSchool.hayClases,
  modality: restSchool.modalidad,
  municipality: restSchool.municipio,
  localityId: restSchool.cod_localidad,
  address: restSchool.domicilio,
  buildingId: restSchool.cod_inmueble,
  support: restSchool.sostenimiento,
  femaleStudent: restSchool.alumnas,
  maleStudent: restSchool.alumnos,
  students: restSchool.sumaAlumnos,
  teachers: restSchool.docentes,
  assistants: restSchool.grupos,
  directors: restSchool.director,
  subDirectors: restSchool.subdirector,
  technicalPedagogicalAdvisers: restSchool.atps,
  physicalEducationTeachers: restSchool.educfis,
  admins: restSchool.admin,
  quartermasters: restSchool.intenden,
  others: restSchool.otros,
  waterSupply: restSchool.tipoAbasAgua,
  waterServiceContinuity: restSchool.contServAgua,
  waterForHandWashing: restSchool.aguaLavamanos,
  sinkSufficiency: restSchool.lavamanos,
  soapSufficiency: restSchool.jabon,
  towelSufficiency: restSchool.toallas,
  sanitizerSufficiency: restSchool.sanitizante,
  binSufficiency: restSchool.botesBasura,
  hasSepticSystem: restSchool.tipoDrenaje,
  hasAbilityToReorganizeSpace: restSchool.espacios,
  hasHygieneCommittee: restSchool.comite,
  alternatesAttendance: restSchool.alterna_asis,
  absentFemaleStudents: restSchool.sumaInaAlumnas,
  absentMaleStudents: restSchool.sumaInaAlumnos,
  studentAbsenceMainReasons: {
    '1': restSchool.inaalum_causa1,
    '2': restSchool.inaalum_causa2,
    '3': restSchool.inaalum_causa3,
    '4': restSchool.inaalum_causa4,
    '5': restSchool.inaalum_causa5,
  },
  studentAbsenceOtherReason: restSchool.inaalum_causaotro,
  absentTeachers: restSchool.sumaInaDocentes,
  teacherAbsenceMainReasons: {
    '1': restSchool.inadoc_causa1,
    '2': restSchool.inadoc_causa2,
    '3': restSchool.inadoc_causa3,
    '4': restSchool.inadoc_causa4,
  },
  teacherAbsenceOtherReason: restSchool.inadoc_causaotro,
  absentAdmins: restSchool.sumaInaAdministrativos,
  adminAbsenceMainReasons: {
    '1': restSchool.inaadm_causa1,
    '2': restSchool.inaadm_causa2,
    '3': restSchool.inaadm_causa3,
    '4': restSchool.inaadm_causa4,
  },
  adminAbsenceOtherReason: restSchool.inaadm_causaotro,
  comments: restSchool.comentarios,
  maleStudentAbsenceProportion: restSchool.indiceAlumnosSobreInasistencias,
  femaleStudentAbsenceProportion: restSchool.indiceAlumnasSobreInasistencias,
  expectedStudents: restSchool.alum_prog,
});
