import { School } from '@/domain/school/School';

export interface RestSchool {
  id: string;
  localidad: string;
  municipioId: string;
  entidadId: string;
  nombre: string;
  alumnasPorcentaje: number;
  alumnosPorcentaje: number;
  docentesPorcentaje: number;
  adminPorcentaje: number;
  nivel: string;
  cct: string;
  turno: string;
  hayClases: 1;
  modalidad: string;
  municipio: string;
  cod_localidad: string;
  domicilio: string;
  cod_inmueble: string;
  sostenimiento: string;
  alumnas: number;
  alumnos: number;
  totAlumnos: number;
  docentes: number;
  grupos: number;
  director: number;
  subdirector: number;
  atps: number;
  educfis: number;
  admin: number;
  intenden: number;
  otros: number;
  tipoaBasagua: number;
  contServAgua: number;
  aguaLavamanos: number;
  lavamanos: number;
  jabon: number;
  toallas: number;
  sanitizante: number;
  botesBasura: number;
  tipoDrenaje: number;
  espacios: number;
  comite: number;
  asistencia50: number;
  inaAlumnas: number;
  inaAlumnos: number;
  inaalum_causa1: number;
  inaalum_causa2: number;
  inaalum_causa3: number;
  inaalum_causa4: number;
  inaalum_causa5: number;
  inaalum_causaotro: string;
  inaDocentes: number;
  inadoc_causa1: number;
  inadoc_causa2: number;
  inadoc_causa3: number;
  inadoc_causa4: number;
  inadoc_causaotro: string;
  inaAdministrativos: number;
  inaadm_causa1: number;
  inaadm_causa2: number;
  inaadm_causa3: number;
  inaadm_causa4: number;
  inaadm_causaotro: string;
  comentarios: string;
}

export const toSchool = (restSchool: RestSchool): School => ({
  id: restSchool.id,
  locality: restSchool.localidad,
  municipalityId: restSchool.municipioId,
  stateId: restSchool.entidadId,
  name: restSchool.nombre,
  femaleStudentAttendance: restSchool.alumnasPorcentaje,
  maleStudentAttendance: restSchool.alumnosPorcentaje,
  teacherAttendance: restSchool.docentesPorcentaje,
  adminAttendance: restSchool.adminPorcentaje,
  level: restSchool.nivel,
  workCenterKey: restSchool.cct,
  turn: restSchool.turno,
  givesClasses: restSchool.hayClases,
  modality: restSchool.modalidad,
  municipality: restSchool.municipio,
  localityId: restSchool.cod_localidad,
  address: restSchool.domicilio,
  buildingId: restSchool.cod_inmueble,
  support: restSchool.sostenimiento,
  femaleStudent: restSchool.alumnas,
  maleStudent: restSchool.alumnos,
  students: restSchool.totAlumnos,
  teachers: restSchool.docentes,
  assistants: restSchool.grupos,
  directors: restSchool.director,
  subDirectors: restSchool.subdirector,
  technicalPedagogicalAdvisers: restSchool.atps,
  physicalEducationTeachers: restSchool.educfis,
  admins: restSchool.admin,
  quartermasters: restSchool.intenden,
  others: restSchool.otros,
  waterSupply: restSchool.tipoaBasagua,
  waterServiceContinuity: restSchool.contServAgua,
  waterForHandWashing: restSchool.aguaLavamanos,
  sinkSufficiency: restSchool.lavamanos,
  soapSufficiency: restSchool.jabon,
  towelSufficiency: restSchool.toallas,
  sanitizerSufficiency: restSchool.sanitizante,
  binSufficiency: restSchool.botesBasura,
  hasSepticSystem: restSchool.tipoDrenaje,
  hasAbilityToReorganizeSpace: restSchool.espacios,
  hasHygieneCommittee: restSchool.comite,
  alternatesAttendance: restSchool.asistencia50,
  absentFemaleStudents: restSchool.inaAlumnas,
  absentMaleStudents: restSchool.inaAlumnos,
  studentAbsenceMainReasons: {
    '1': restSchool.inaalum_causa1,
    '2': restSchool.inaalum_causa2,
    '3': restSchool.inaalum_causa3,
    '4': restSchool.inaalum_causa4,
    '5': restSchool.inaalum_causa5,
  },
  studentAbsenceOtherReason: restSchool.inaalum_causaotro,
  absentTeachers: restSchool.inaDocentes,
  teacherAbsenceMainReasons: {
    '1': restSchool.inadoc_causa1,
    '2': restSchool.inadoc_causa2,
    '3': restSchool.inadoc_causa3,
    '4': restSchool.inadoc_causa4,
  },
  teacherAbsenceOtherReason: restSchool.inadoc_causaotro,
  absentAdmins: restSchool.inaAdministrativos,
  adminAbsenceMainReasons: {
    '1': restSchool.inaadm_causa1,
    '2': restSchool.inaadm_causa2,
    '3': restSchool.inaadm_causa3,
    '4': restSchool.inaadm_causa4,
  },
  adminAbsenceOtherReason: restSchool.inaadm_causaotro,
  comments: restSchool.comentarios,
});
