import { School } from '@/domain/school/School';

export interface RestSchool {
  id: string;
  nombre: string;
  localidad: string;
  nivel: string;
  municipioId: string;
  entidadId: string;
  alumnosInasistencia: number;
  docentesInasistencia: number;
  adminInasistencia: number;
  totalAlum: number;
  cct: string;
  turno: string;
  sostenimiento: string;
  hayclases: number;
  alum1ro: number;
  alum2do: number;
  alum3ro: number;
  alum4to: number;
  alum5to: number;
  alum6to: number;
  docente1ro: number;
  docente2do: number;
  docente3ro: number;
  docente4to: number;
  docente5to: number;
  docente6to: number;
  gpos1ro: number;
  gpos2do: number;
  gpos3ro: number;
  gpos4to: number;
  gpos5to: number;
  gpos6to: number;
  inaalum1ro: number;
  inaalum2do: number;
  inaalum3ro: number;
  inaalum4to: number;
  inaalum5to: number;
  inaalum6to: number;
  inadocente1ro: number;
  inadocente2do: number;
  inadocente3ro: number;
  inadocente4to: number;
  inadocente5to: number;
  inadocente6to: number;
  director: number;
  subdirector: number;
  atps: number;
  educfis: number;
  admin: number;
  intenden: number;
  otros: number;
  inadirector: number;
  inasubdirector: number;
  inaatps: number;
  inaeducfis: number;
  inaadmin: number;
  inaintenden: number;
  inaotros: number;
  causaInaAlum: number;
  tipoaBasagua: number;
  contServagua: number;
  lavamanos: number;
  jabon: number;
  toallas: number;
  sanitizante: number;
  botesBasura: number;
  tipodrenaje: number;
  espacios: number;
}

export const toSchool = (restSchool: RestSchool): School => ({
  id: `${restSchool.id}__${restSchool.nivel}`,
  name: restSchool.nombre,
  locality: restSchool.localidad,
  municipalityId: restSchool.municipioId,
  stateId: restSchool.entidadId,
  studentAbsenceRate: restSchool.alumnosInasistencia,
  teacherAbsenceRate: restSchool.docentesInasistencia,
  adminAbsenceRate: restSchool.adminInasistencia,
  students: restSchool.totalAlum,
  level: restSchool.nivel,
  workCenterKey: restSchool.cct,
  turn: restSchool.turno,
  type: restSchool.sostenimiento,
  givesClasses: restSchool.hayclases,
  studentsFirstGrade: restSchool.alum1ro,
  studentsSecondGrade: restSchool.alum2do,
  studentsThirdGrade: restSchool.alum3ro,
  studentsFourthGrade: restSchool.alum4to,
  studentsFifthGrade: restSchool.alum5to,
  studentsSixthGrade: restSchool.alum6to,
  teachersFirstGrade: restSchool.docente1ro,
  teachersSecondGrade: restSchool.docente2do,
  teachersThirdGrade: restSchool.docente3ro,
  teachersFourthGrade: restSchool.docente4to,
  teachersFifthGrade: restSchool.docente5to,
  teachersSixthGrade: restSchool.docente6to,
  assistantsFirstGrade: restSchool.gpos1ro,
  assistantsSecondGrade: restSchool.gpos2do,
  assistantsThirdGrade: restSchool.gpos3ro,
  assistantsFourthGrade: restSchool.gpos4to,
  assistantsFifthGrade: restSchool.gpos5to,
  assistantsSixthGrade: restSchool.gpos6to,
  absentStudentsFirstGrade: restSchool.inaalum1ro,
  absentStudentsSecondGrade: restSchool.inaalum2do,
  absentStudentsThirdGrade: restSchool.inaalum3ro,
  absentStudentsFourthGrade: restSchool.inaalum4to,
  absentStudentsFifthGrade: restSchool.inaalum5to,
  absentStudentsSixthGrade: restSchool.inaalum6to,
  absentTeachersFirstGrade: restSchool.inadocente1ro,
  absentTeachersSecondGrade: restSchool.inadocente2do,
  absentTeachersThirdGrade: restSchool.inadocente3ro,
  absentTeachersFourthGrade: restSchool.inadocente4to,
  absentTeachersFifthGrade: restSchool.inadocente5to,
  absentTeachersSixthGrade: restSchool.inadocente6to,
  directors: restSchool.director,
  subDirector: restSchool.subdirector,
  technicalPedagogicalAdvisers: restSchool.atps,
  physicalEducationTeachers: restSchool.educfis,
  administrativeStaff: restSchool.admin,
  quartermasterStaff: restSchool.intenden,
  others: restSchool.otros,
  absentDirectors: restSchool.inadirector,
  absentSubDirector: restSchool.inasubdirector,
  absentTechnicalPedagogicalAdvisers: restSchool.inaatps,
  absentPhysicalEducationTeachers: restSchool.inaeducfis,
  absentAdministrativeStaff: restSchool.inaadmin,
  absentQuartermasterStaff: restSchool.inaintenden,
  absentOthers: restSchool.inaotros,
  studentAbsenceMainReason: restSchool.causaInaAlum,
  waterSupply: restSchool.tipoaBasagua,
  waterServiceContinuity: restSchool.contServagua,
  sinkSufficiency: restSchool.lavamanos,
  soapSufficiency: restSchool.jabon,
  towelSufficiency: restSchool.toallas,
  sanitizerSufficiency: restSchool.sanitizante,
  binSufficiency: restSchool.botesBasura,
  hasSepticSystem: restSchool.tipodrenaje,
  hasAbilityToReorganizeSpace: restSchool.espacios,
});
