import { makeAdministrativeDivision } from '../AdministrativeDivision.fixture';

import { AdministrativeDivisionDataSet, toAdministrativeDivisionDataset } from '@/primary/common/AdministrativeDivisionDataSet';
import { toNumericDataSet } from '@/primary/common/NumericDataSet';
import { toPercentageDataSet } from '@/primary/common/PercentageDataSet';

describe('AdministrativeDivisionDataSet', () => {
  it('should transform AdministrativeDivision to AdministrativeDivisionDataSet', () => {
    const administrativeDivision = makeAdministrativeDivision({ id: '0' });
    expect(toAdministrativeDivisionDataset(administrativeDivision)).toEqual<AdministrativeDivisionDataSet>({
      support: { private: toPercentageDataSet(0.3), public: toPercentageDataSet(0.7) },
      studentAttendance: toPercentageDataSet(0.74),
      teacherAttendance: toPercentageDataSet(0.97),
      adminAttendance: toPercentageDataSet(0.98),
      maleStudentAbsencePercentageOverStudentAbsence: toPercentageDataSet(0.12),
      femaleStudentAbsencePercentageOverStudentAbsence: toPercentageDataSet(0.14),
      schools: '759',
      students: toNumericDataSet(101837),
      femaleStudents: toNumericDataSet(50196),
      maleStudents: toNumericDataSet(51641),
      maleStudentPercentage: toPercentageDataSet(0.51),
      femaleStudentPercentage: toPercentageDataSet(0.49),
      teachers: '4058',
      assistants: '4060',
      directors: '590',
      subDirectors: '291',
      technicalPedagogicalAdvisers: '0',
      physicalEducationTeachers: '539',
      admins: '2192',
      quartermasters: '1022',
      others: '0',
      schoolGivingClasses: {
        '1': toNumericDataSet(607),
        '2': toNumericDataSet(30),
        '3': toNumericDataSet(21),
        '4': toNumericDataSet(29),
        '5': toNumericDataSet(25),
        '6': toNumericDataSet(17),
        '7': toNumericDataSet(30),
        '8': toNumericDataSet(45),
      },
      schoolGivingClassesPercentages: {
        '1': toPercentageDataSet(0.8),
        '2': toPercentageDataSet(0.04),
        '3': toPercentageDataSet(0.03),
        '4': toPercentageDataSet(0.04),
        '5': toPercentageDataSet(0.03),
        '6': toPercentageDataSet(0.02),
        '7': toPercentageDataSet(0.04),
        '8': toPercentageDataSet(0.1),
      },
      schoolWaterSupply: { '1': toNumericDataSet(196), '2': toNumericDataSet(185), '3': toNumericDataSet(188), '4': toNumericDataSet(190) },
      schoolWaterSupplyPercentages: {
        '1': toPercentageDataSet(0.26),
        '2': toPercentageDataSet(0.24),
        '3': toPercentageDataSet(0.25),
        '4': toPercentageDataSet(0.25),
      },
      schoolWaterServiceContinuity: {
        '1': toNumericDataSet(202),
        '2': toNumericDataSet(191),
        '3': toNumericDataSet(176),
        '4': toNumericDataSet(190),
      },
      schoolWaterServiceContinuityPercentages: {
        '1': toPercentageDataSet(0.27),
        '2': toPercentageDataSet(0.25),
        '3': toPercentageDataSet(0.23),
        '4': toPercentageDataSet(0.25),
      },
      schoolWithWaterForHandWashing: { '1': toNumericDataSet(301), '2': toNumericDataSet(458) },
      schoolWithWaterForHandWashingPercentages: { '1': toPercentageDataSet(0.4), '2': toPercentageDataSet(0.6) },
      schoolFunctionalSinkCount: toNumericDataSet(228),
      schoolSoapSufficiency: { '1': toNumericDataSet(249), '2': toNumericDataSet(248), '3': toNumericDataSet(262) },
      schoolSoapSufficiencyPercentages: { '1': toPercentageDataSet(0.33), '2': toPercentageDataSet(0.33), '3': toPercentageDataSet(0.35) },
      schoolTowelSufficiency: { '1': toNumericDataSet(256), '2': toNumericDataSet(244), '3': toNumericDataSet(259) },
      schoolTowelSufficiencyPercentages: { '1': toPercentageDataSet(0.34), '2': toPercentageDataSet(0.32), '3': toPercentageDataSet(0.34) },
      schoolSanitizerSufficiency: { '1': toNumericDataSet(254), '2': toNumericDataSet(251), '3': toNumericDataSet(254) },
      schoolSanitizerSufficiencyPercentages: {
        '1': toPercentageDataSet(0.33),
        '2': toPercentageDataSet(0.33),
        '3': toPercentageDataSet(0.33),
      },
      schoolBinSufficiency: { '1': toNumericDataSet(270), '2': toNumericDataSet(489) },
      schoolBinSufficiencyPercentages: { '1': toPercentageDataSet(0.36), '2': toPercentageDataSet(0.64) },
      schoolWithSepticSystem: { '1': toNumericDataSet(372), '2': toNumericDataSet(387) },
      schoolWithSepticSystemPercentages: { '1': toPercentageDataSet(0.49), '2': toPercentageDataSet(0.51) },
      schoolWithAbilityToReorganizeSpace: { '1': toNumericDataSet(359), '2': toNumericDataSet(400) },
      schoolWithAbilityToReorganizeSpacePercentages: { '1': toPercentageDataSet(0.47), '2': toPercentageDataSet(0.53) },
      hygieneCommittee: { '1': toNumericDataSet(298), '2': toNumericDataSet(461) },
      hygieneCommitteePercentages: { '1': toPercentageDataSet(0.39), '2': toPercentageDataSet(0.61) },
      alternatesAttendance: { '1': toNumericDataSet(263), '2': toNumericDataSet(496) },
      alternatesAttendancePercentages: { '1': toPercentageDataSet(0.35), '2': toPercentageDataSet(0.65) },
      absentFemaleStudents: '9747',
      absentMaleStudents: '8233',
      studentAbsenceMainReasons: {
        '1': toNumericDataSet(379),
        '2': toNumericDataSet(5733),
        '3': toNumericDataSet(1551),
        '4': toNumericDataSet(6957),
        '5': toNumericDataSet(3360),
      },
      studentAbsenceMainReasonsPercentages: {
        '1': toPercentageDataSet(0.02),
        '2': toPercentageDataSet(0.32),
        '3': toPercentageDataSet(0.09),
        '4': toPercentageDataSet(0.39),
        '5': toPercentageDataSet(0.19),
      },
      absentTeachers: '171',
      teacherAbsenceMainReasons: {
        '1': toNumericDataSet(0),
        '2': toNumericDataSet(171),
        '3': toNumericDataSet(0),
        '4': toNumericDataSet(0),
      },
      teacherAbsenceMainReasonsPercentages: {
        '1': toPercentageDataSet(0),
        '2': toPercentageDataSet(1),
        '3': toPercentageDataSet(0),
        '4': toPercentageDataSet(0),
      },
      absentAdmins: '83',
      adminsAbsenceMainReasons: { '1': toNumericDataSet(0), '2': toNumericDataSet(83), '3': toNumericDataSet(0), '4': toNumericDataSet(0) },
      adminsAbsenceMainReasonsPercentages: {
        '1': toPercentageDataSet(0),
        '2': toPercentageDataSet(1),
        '3': toPercentageDataSet(0),
        '4': toPercentageDataSet(0),
      },
      takenActions: {
        visits: toNumericDataSet(314),
        calls: toNumericDataSet(301),
        scholarship: toNumericDataSet(299),
        none: toNumericDataSet(299),
      },
      takenActionsPercentages: {
        visits: toPercentageDataSet(0.41),
        calls: toPercentageDataSet(0.4),
        scholarship: toPercentageDataSet(0.39),
        none: toPercentageDataSet(0.39),
      },
      drinkers: toNumericDataSet(1024),
      maleStudentToilets: toNumericDataSet(2268),
      femaleStudentToilets: toNumericDataSet(2281),
      foodSupport: { '1': toNumericDataSet(336), '2': toNumericDataSet(423) },
      foodSupportPercentages: { '1': toPercentageDataSet(0.44), '2': toPercentageDataSet(0.56) },
      foodSupportType: {
        dif: toNumericDataSet(172),
        fullTimeProgram: toNumericDataSet(160),
        state: toNumericDataSet(177),
        others: toNumericDataSet(168),
      },
      foodSupportTypePercentages: {
        dif: toPercentageDataSet(0.23),
        fullTimeProgram: toPercentageDataSet(0.21),
        state: toPercentageDataSet(0.23),
        others: toPercentageDataSet(0.22),
      },
      theSchoolIsOurs: { '1': toNumericDataSet(319), '2': toNumericDataSet(440) },
      theSchoolIsOursPercentages: { '1': toPercentageDataSet(0.42), '2': toPercentageDataSet(0.58) },
    });
  });

  it('should set default value for administrative division data set', () => {
    expect(toAdministrativeDivisionDataset(undefined)).toEqual<AdministrativeDivisionDataSet>({
      support: { private: toPercentageDataSet(-1), public: toPercentageDataSet(-1) },
      studentAttendance: toPercentageDataSet(-1),
      teacherAttendance: toPercentageDataSet(-1),
      adminAttendance: toPercentageDataSet(-1),
      maleStudentAbsencePercentageOverStudentAbsence: toPercentageDataSet(-1),
      femaleStudentAbsencePercentageOverStudentAbsence: toPercentageDataSet(-1),
      schools: '-',
      students: toNumericDataSet(-1),
      femaleStudents: toNumericDataSet(-1),
      maleStudents: toNumericDataSet(-1),
      maleStudentPercentage: toPercentageDataSet(-1),
      femaleStudentPercentage: toPercentageDataSet(-1),
      teachers: '-',
      assistants: '-',
      directors: '-',
      subDirectors: '-',
      technicalPedagogicalAdvisers: '-',
      physicalEducationTeachers: '-',
      admins: '-',
      quartermasters: '-',
      others: '-',
      schoolGivingClasses: {
        '1': toNumericDataSet(-1),
        '2': toNumericDataSet(-1),
        '3': toNumericDataSet(-1),
        '4': toNumericDataSet(-1),
        '5': toNumericDataSet(-1),
        '6': toNumericDataSet(-1),
        '7': toNumericDataSet(-1),
        '8': toNumericDataSet(-1),
      },
      schoolGivingClassesPercentages: {
        '1': toPercentageDataSet(-1),
        '2': toPercentageDataSet(-1),
        '3': toPercentageDataSet(-1),
        '4': toPercentageDataSet(-1),
        '5': toPercentageDataSet(-1),
        '6': toPercentageDataSet(-1),
        '7': toPercentageDataSet(-1),
        '8': toPercentageDataSet(-1),
      },
      schoolWaterSupply: { '1': toNumericDataSet(-1), '2': toNumericDataSet(-1), '3': toNumericDataSet(-1), '4': toNumericDataSet(-1) },
      schoolWaterSupplyPercentages: {
        '1': toPercentageDataSet(-1),
        '2': toPercentageDataSet(-1),
        '3': toPercentageDataSet(-1),
        '4': toPercentageDataSet(-1),
      },
      schoolWaterServiceContinuity: {
        '1': toNumericDataSet(-1),
        '2': toNumericDataSet(-1),
        '3': toNumericDataSet(-1),
        '4': toNumericDataSet(-1),
      },
      schoolWaterServiceContinuityPercentages: {
        '1': toPercentageDataSet(-1),
        '2': toPercentageDataSet(-1),
        '3': toPercentageDataSet(-1),
        '4': toPercentageDataSet(-1),
      },
      schoolWithWaterForHandWashing: { '1': toNumericDataSet(-1), '2': toNumericDataSet(-1) },
      schoolWithWaterForHandWashingPercentages: { '1': toPercentageDataSet(-1), '2': toPercentageDataSet(-1) },
      schoolFunctionalSinkCount: toNumericDataSet(-1),
      schoolSoapSufficiency: { '1': toNumericDataSet(-1), '2': toNumericDataSet(-1), '3': toNumericDataSet(-1) },
      schoolSoapSufficiencyPercentages: { '1': toPercentageDataSet(-1), '2': toPercentageDataSet(-1), '3': toPercentageDataSet(-1) },
      schoolTowelSufficiency: { '1': toNumericDataSet(-1), '2': toNumericDataSet(-1), '3': toNumericDataSet(-1) },
      schoolTowelSufficiencyPercentages: { '1': toPercentageDataSet(-1), '2': toPercentageDataSet(-1), '3': toPercentageDataSet(-1) },
      schoolSanitizerSufficiency: { '1': toNumericDataSet(-1), '2': toNumericDataSet(-1), '3': toNumericDataSet(-1) },
      schoolSanitizerSufficiencyPercentages: {
        '1': toPercentageDataSet(-1),
        '2': toPercentageDataSet(-1),
        '3': toPercentageDataSet(-1),
      },
      schoolBinSufficiency: { '1': toNumericDataSet(-1), '2': toNumericDataSet(-1) },
      schoolBinSufficiencyPercentages: { '1': toPercentageDataSet(-1), '2': toPercentageDataSet(-1) },
      schoolWithSepticSystem: { '1': toNumericDataSet(-1), '2': toNumericDataSet(-1) },
      schoolWithSepticSystemPercentages: { '1': toPercentageDataSet(-1), '2': toPercentageDataSet(-1) },
      schoolWithAbilityToReorganizeSpace: { '1': toNumericDataSet(-1), '2': toNumericDataSet(-1) },
      schoolWithAbilityToReorganizeSpacePercentages: { '1': toPercentageDataSet(-1), '2': toPercentageDataSet(-1) },
      hygieneCommittee: { '1': toNumericDataSet(-1), '2': toNumericDataSet(-1) },
      hygieneCommitteePercentages: { '1': toPercentageDataSet(-1), '2': toPercentageDataSet(-1) },
      alternatesAttendance: { '1': toNumericDataSet(-1), '2': toNumericDataSet(-1) },
      alternatesAttendancePercentages: { '1': toPercentageDataSet(-1), '2': toPercentageDataSet(-1) },
      absentFemaleStudents: '-',
      absentMaleStudents: '-',
      studentAbsenceMainReasons: {
        '1': toNumericDataSet(-1),
        '2': toNumericDataSet(-1),
        '3': toNumericDataSet(-1),
        '4': toNumericDataSet(-1),
        '5': toNumericDataSet(-1),
      },
      studentAbsenceMainReasonsPercentages: {
        '1': toPercentageDataSet(-1),
        '2': toPercentageDataSet(-1),
        '3': toPercentageDataSet(-1),
        '4': toPercentageDataSet(-1),
        '5': toPercentageDataSet(-1),
      },
      absentTeachers: '-',
      teacherAbsenceMainReasons: {
        '1': toNumericDataSet(-1),
        '2': toNumericDataSet(-1),
        '3': toNumericDataSet(-1),
        '4': toNumericDataSet(-1),
      },
      teacherAbsenceMainReasonsPercentages: {
        '1': toPercentageDataSet(-1),
        '2': toPercentageDataSet(-1),
        '3': toPercentageDataSet(-1),
        '4': toPercentageDataSet(-1),
      },
      absentAdmins: '-',
      adminsAbsenceMainReasons: {
        '1': toNumericDataSet(-1),
        '2': toNumericDataSet(-1),
        '3': toNumericDataSet(-1),
        '4': toNumericDataSet(-1),
      },
      adminsAbsenceMainReasonsPercentages: {
        '1': toPercentageDataSet(-1),
        '2': toPercentageDataSet(-1),
        '3': toPercentageDataSet(-1),
        '4': toPercentageDataSet(-1),
      },
      takenActions: {
        visits: toNumericDataSet(-1),
        calls: toNumericDataSet(-1),
        scholarship: toNumericDataSet(-1),
        none: toNumericDataSet(-1),
      },
      takenActionsPercentages: {
        visits: toPercentageDataSet(-1),
        calls: toPercentageDataSet(-1),
        scholarship: toPercentageDataSet(-1),
        none: toPercentageDataSet(-1),
      },
      drinkers: toNumericDataSet(-1),
      maleStudentToilets: toNumericDataSet(-1),
      femaleStudentToilets: toNumericDataSet(-1),
      foodSupport: { '1': toNumericDataSet(-1), '2': toNumericDataSet(-1) },
      foodSupportPercentages: { '1': toPercentageDataSet(-1), '2': toPercentageDataSet(-1) },
      foodSupportType: {
        dif: toNumericDataSet(-1),
        fullTimeProgram: toNumericDataSet(-1),
        state: toNumericDataSet(-1),
        others: toNumericDataSet(-1),
      },
      foodSupportTypePercentages: {
        dif: toPercentageDataSet(-1),
        fullTimeProgram: toPercentageDataSet(-1),
        state: toPercentageDataSet(-1),
        others: toPercentageDataSet(-1),
      },
      theSchoolIsOurs: { '1': toNumericDataSet(-1), '2': toNumericDataSet(-1) },
      theSchoolIsOursPercentages: { '1': toPercentageDataSet(-1), '2': toPercentageDataSet(-1) },
    });
  });
});
