import { AdministrativeDivisionTypes } from '@/domain/administrative-division/AdministrativeDivisionTypes';

export interface AdministrativeDivision {
  id: string;
  name: string;
  type: AdministrativeDivisionTypes;
  stateId: string;
  totalSchools: number;
  totalStudent: number;
  studentAbsenceRate: number;
  teacherAbsenceRate: number;
  adminAbsenceRate: number;
  schoolGivingClassesPercentages: { [key: string]: number };
  studentsFirstGrade: number;
  studentsSecondGrade: number;
  studentsThirdGrade: number;
  studentsFourthGrade: number;
  studentsFifthGrade: number;
  studentsSixthGrade: number;
  teachersFirstGrade: number;
  teachersSecondGrade: number;
  teachersThirdGrade: number;
  teachersFourthGrade: number;
  teachersFifthGrade: number;
  teachersSixthGrade: number;
  assistantsFirstGrade: number;
  assistantsSecondGrade: number;
  assistantsThirdGrade: number;
  assistantsFourthGrade: number;
  assistantsFifthGrade: number;
  assistantsSixthGrade: number;
  absentStudentsFirstGrade: number;
  absentStudentsSecondGrade: number;
  absentStudentsThirdGrade: number;
  absentStudentsFourthGrade: number;
  absentStudentsFifthGrade: number;
  absentStudentsSixthGrade: number;
  absentTeachersFirstGrade: number;
  absentTeachersSecondGrade: number;
  absentTeachersThirdGrade: number;
  absentTeachersFourthGrade: number;
  absentTeachersFifthGrade: number;
  absentTeachersSixthGrade: number;
  directors: number;
  subDirector: number;
  technicalPedagogicalAdvisers: number;
  physicalEducationTeachers: number;
  administrativeStaff: number;
  quartermasterStaff: number;
  others: number;
  absentDirectors: number;
  absentSubDirector: number;
  absentTechnicalPedagogicalAdvisers: number;
  absentPhysicalEducationTeachers: number;
  absentAdministrativeStaff: number;
  absentQuartermasterStaff: number;
  absentOthers: number;
  studentAbsenceMainReasonPercentages: { [key: string]: number };
  schoolWaterSupplyPercentages: { [key: string]: number };
  schoolWaterServiceContinuityPercentages: { [key: string]: number };
  schoolWithWaterForHandWashingPercentages: { [key: string]: number };
  schoolSinkSufficiencyPercentages: { [key: string]: number };
  schoolSoapSufficiencyPercentages: { [key: string]: number };
  schoolTowelSufficiencyPercentages: { [key: string]: number };
  schoolSanitizerSufficiencyPercentages: { [key: string]: number };
  schoolBinSufficiencyPercentages: { [key: string]: number };
  schoolWithSepticSystemPercentages: { [key: string]: number };
  schoolWithAbilityToReorganizeSpacePercentages: { [key: string]: number };
}
