import { AdministrativeDivisionTypes } from '@/domain/administrative-division/AdministrativeDivisionTypes';
import { LocalDate } from '@/domain/date/LocalDate';

export interface AdministrativeDivision {
  id: string;
  name: string;
  lastUpdateDate: LocalDate;
  type: AdministrativeDivisionTypes;
  stateId: string;
  support: { private: number; public: number };
  studentAttendance: number;
  teacherAttendance: number;
  adminAttendance: number;
  schools: number;
  students: number;
  femaleStudents: number;
  maleStudents: number;
  teachers: number;
  assistants: number;
  directors: number;
  subDirectors: number;
  technicalPedagogicalAdvisers: number;
  physicalEducationTeachers: number;
  admins: number;
  quartermasters: number;
  others: number;
  schoolGivingClasses: { [key: string]: number };
  schoolWaterSupply: { [key: string]: number };
  schoolWaterServiceContinuity: { [key: string]: number };
  schoolWithWaterForHandWashing: { [key: string]: number };
  schoolSinkSufficiency: { [key: string]: number };
  schoolSoapSufficiency: { [key: string]: number };
  schoolTowelSufficiency: { [key: string]: number };
  schoolSanitizerSufficiency: { [key: string]: number };
  schoolBinSufficiency: { [key: string]: number };
  schoolWithSepticSystem: { [key: string]: number };
  schoolWithAbilityToReorganizeSpace: { [key: string]: number };
  hygieneCommittee: { [key: string]: number };
  alternatesAttendance: { [key: string]: number };
  absentFemaleStudents: number;
  absentMaleStudents: number;
  studentAbsenceMainReasons: { [key: string]: number };
  studentAbsenceMainReasonsPercentages: { [key: string]: number };
  absentTeachers: number;
  teacherAbsenceMainReasons: { [key: string]: number };
  teacherAbsenceMainReasonsPercentages: { [key: string]: number };
  absentAdmins: number;
  adminAbsenceMainReasons: { [key: string]: number };
  adminAbsenceMainReasonsPercentages: { [key: string]: number };
}
