import { LocalDate } from '@/domain/date/LocalDate';
import { School } from '@/domain/school/School';

const defaultSchool: School = {
  id: '03KJN0025W4',
  locality: 'LA CANDELARIA',
  municipalityId: '008',
  stateId: '03',
  name: 'CURSO COMUNITARIO DE EDUCACION PREESCOLAR',
  lastUpdateDate: LocalDate.of('2020-06-16'),
  studentAttendance: 1,
  maleStudentAbsencePercentageOverStudentAbsence: 0,
  femaleStudentAbsencePercentageOverStudentAbsence: 0,
  teacherAttendance: 1,
  adminAttendance: -1,
  level: 'PREESCOLAR',
  workCenterKey: '03KJN0025W',
  turn: '4',
  givesClasses: 1,
  modality: 'PREESCOLAR COMUNITARIO',
  municipality: 'LOS CABOS',
  localityId: '0063',
  address: 'NINGUNO NINGUNO',
  buildingId: '03INM0636F',
  support: 'PÚBLICO',
  femaleStudent: 1,
  maleStudent: 5,
  maleStudentPercentage: 0.83,
  femaleStudentPercentage: 0.17,
  students: 6,
  teachers: 1,
  assistants: 1,
  directors: 0,
  subDirectors: 0,
  technicalPedagogicalAdvisers: 0,
  physicalEducationTeachers: 0,
  admins: 0,
  quartermasters: 0,
  others: 0,
  waterSupply: 2,
  waterServiceContinuity: 2,
  waterForHandWashing: 1,
  functionalSinkCount: 2,
  soapSufficiency: 1,
  towelSufficiency: 3,
  sanitizerSufficiency: 1,
  binSufficiency: 2,
  hasSepticSystem: 2,
  hasAbilityToReorganizeSpace: 1,
  hasHygieneCommittee: 1,
  alternatesAttendance: 1,
  absentFemaleStudents: 0,
  absentMaleStudents: 0,
  studentAbsenceMainReasons: {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
  },
  studentAbsenceMainReasonsPercentages: {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
  },
  studentAbsenceOtherReason: '',
  absentTeachers: 0,
  teacherAbsenceMainReasons: {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
  },
  teacherAbsenceMainReasonsPercentages: {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
  },
  teacherAbsenceOtherReason: '',
  absentAdmins: 0,
  adminAbsenceMainReasons: {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
  },
  adminAbsenceMainReasonsPercentages: {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
  },
  adminAbsenceOtherReason: '',
  comments: '',
  maleStudentAbsenceProportion: -1,
  femaleStudentAbsenceProportion: -1,
  expectedStudents: 3,
  takenActions: { visits: false, calls: true, scholarship: true, none: false },
  drinkers: 5,
  maleStudentToilets: 2,
  femaleStudentToilets: 2,
  foodSupport: true,
  foodSupportType: { dif: false, fullTimeProgram: true, state: false, others: true },
  foodSupportComment: '',
  theSchoolIsOurs: 1,
  electricitySource: 3,
  internetAccess: 1,
};

export const makeSchool = (override: Partial<School> = {}) => ({
  ...defaultSchool,
  ...override,
});
